<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>PayloadContent</key>
		<array>
			<dict>
				<key>APNs</key>
				<array>
					<dict>
						<key>AllowedProtocolMask</key>
						<integer>1</integer>
						<key>AllowedProtocolMaskInDomesticRoaming</key>
						<integer>1</integer>
						<key>AllowedProtocolMaskInRoaming</key>
						<integer>1</integer>
						<key>AuthenticationType</key>
						<string>CHAP</string>
						<key>DefaultProtocolMask</key>
						<integer>1</integer>
						<key>EnableXLAT464</key>
						<true />
						<key>Name</key>
						<string>mcinet</string>
					</dict>
					<dict>
						<key>AllowedProtocolMask</key>
						<integer>1</integer>
						<key>AllowedProtocolMaskInDomesticRoaming</key>
						<integer>1</integer>
						<key>AllowedProtocolMaskInRoaming</key>
						<integer>1</integer>
						<key>AuthenticationType</key>
						<string>PAP</string>
						<key>DefaultProtocolMask</key>
						<integer>1</integer>
						<key>EnableXLAT464</key>
						<true />
						<key>Name</key>
						<string>mcinet</string>
					</dict>
				</array>
				<key>PayloadDisplayName</key>
				<string>Cellular</string>
				<key>PayloadIdentifier</key>
				<string>com.apple.cellular.1151236d-36c4-4d89-8f80-392d167c104d</string>
				<key>PayloadType</key>
				<string>com.apple.cellular</string>
				<key>PayloadUUID</key>
				<string>c25b9415-e1ea-4713-b48d-03c3dd5e3de9</string>
				<key>PayloadVersion</key>
				<integer>1</integer>
			</dict>
		</array>
		<key>PayloadDisplayName</key>
		<string>IMEI351542662212758</string>
		<key>PayloadIdentifier</key>
		<string>ab70249a-44de-4dd3-b5bb-c6be267e68a7</string>
		<key>PayloadType</key>
		<string>Configuration</string>
		<key>PayloadUUID</key>
		<string>0270eb75-b990-4bfd-971e-1ead0e45be18</string>
		<key>PayloadVersion</key>
		<integer>1</integer>
	</dict>
</plist>
